socketsupply/components

src/input/README.md, src/input/index.js
Previously, if you set an `tonic-input` width to `50%`, it would set the inner input element also to `50%`, resulting in a `25%` wide input. 
Therefore the inner input should always be `100%` of the parent.
=> Inner input should always be full width of parent

.testcaferc.json, package-lock.json, package.json, test/fixtures/test-form.js, test/fixtures/testcafe.js, test/testcafe/test-form.js
This adds a test using the `testcafe` browser automation
library. 
I only added a small trivial test, I noticed that clicking
a `tonic-button` can sometimes be slow with `testcafe` but 
I couldn't reproduce it.
This is an example test, where we can basically add non-trivial
regression tests to in the future as we fix more issues.
=> tests: Add testcafe

button/index.js, chart/index.js, docs/bundle.js, docs/test.js, input/index.js, package.json, toaster-inline/index.js
This fixes some edge cases in components. namely the following
- Update `tonic-toaster-inline` to add more state in reRender.
This component is now reRender safe so you can update the display
state and `show()` & `hide()` persist among `reRender()`
- Update `tonic-input` ; Improve event handling and value handling
- Update `chart` ; support browserify
- Update `button` support `form` getter.
=> fixes: input, toaster, form

README.md, accordion/index.js, accordion/test.js, badge/index.js, badge/test.js, checkbox/index.js, index.js, input/index.js, mode.js, profile-image/index.js, progress-bar/index.js, range/index.js, router/index.js, router/test.js, tabs/index.js, tabs/test.js, test/index.js, textarea/index.js, textarea/test.js, toggle/index.js, windowed/index.js
The way `tonic` works is that only components that have an `id`
attribute in the HTML / DOM will have their `state` persisted
between `reRender` calls.
To improve developer experience and reduce confusion the
components that rely on `this.state` or `this.props.id` now have
their id set as mandatory in the `render()` method.
There are a few components like `tonic-textarea` that do not
have state at the moment but still have a mandatory id; this is
because they use `this.props.id` in `render()` and would actually
put `tonic--textarea_undefined` in the DOM / HTML if the `id`
is unset. This leads to duplicate `id`'s in the HTML / DOM if
you use multiple `tonic-textarea`
This is a breaking change and will require a major version
bump.
=> src: Make props.id mandatory

checkbox/README.md, checkbox/index.js
This allows for rendering a checkbox that is not actually
manually checkable. For example you might want to render
a checkbox in a row of a table where you already have existing
logic for selecting and multi selecting rows in that table.
With a virtual checkbox you can quickly show the user that the
rows are checked or unchecked by setting `checkbox.value = bool`
whenever the rows are selected or unselected.
=> Support virtual checkbox

checkbox/index.js, docs/bundle.js, docs/index.html, docs/test.js
When controlling a checkbox manually like for example
a "check all" checkbox that you want to keep in sync with
individual checkable items you want to set the state of whether
it's checked or not via properties.
The current implementation only allows setting the default
checked state as true or false and all future state is purely
coming from `this.state` ;
This change makes it respect the checked property and makes
the component declarative and re-render friendly by being able
to update the checked state in `render()` instead of having to
do `querySelector(checkbox).value = x` to update the checked
state.
=> checkbox: Respect properties

windowed/index.js
These are a collection of improvements for streaming
into a windowed component.
- Expose setInnerHeight()
- Recycle dom elems in __overflow__
- Scroll back to visible elem after prepend.
r: @heapwolf
=> Windowed: Improvements for streaming

form/index.js, package-lock.json, package.json, windowed/index.js
This was causing weird behavior for the logs app
where it starts scrolling to the "current visible" row.
Instead if the index is 0 ; aka i am looking at the top,
I should just keep looking at the top.
=> Improve windowed auto scrolling

input/index.js, input/test.js
On the `TonicInput` component we trigger the input event twice.
For focus & blur the `relay()` function is necessary since the
DOM `blur` & `focus` events do not bubble.
However the `input` event already bubbles so we do not have to
relay it, otherwise the outer component event listener gets
called twice and does duplicate work.
=> input: Do not relay `input` event.

windowed/index.js
- Fix different behavior in `unshift()` & `splice()`
- Enforce that `maxRows` must be multiple of `rowsPerPage` ; If `maxRows` is not a multiple then there's boundary bugs I've not found yet ... 
- Make `popCounter` & `prependCounter` seperate counters.
- Remove the `page` re-use logic when a truncate happens ( aka popCounter & shiftCounter ). This logic is broken and lead to the same page being inserted into the DOM multiple times which leads to visually duplicate rows rendered on top of each other.
=> Windowed patches

windowed/index.js
Ran into this issue by using `clear()` to reset a `Windowed` component and load a new Query into it.
=> src: Fix null pointer for this.rows

tabs/README.md, tabs/index.js
This allows a Tonic component embedded inside a Tab to
be notified when it is made visible.
This could be implemented manually but since the Tab is toggled
both by clicks and by keyboard presses the outer component
would have to either handle both or have a buggy keyboard impl.
=> Tabs: Emit tabshow event

dialog/index.js, toaster-inline/index.js
if you have for example a toaster (which has a close button) inside a dialog, this will prevent closing the toaster from also closing the dialog.
=> Fix close button behavior

windowed/index.js
The gaurd for rendering loading bottom & top should be a bit
more specific.
If we gaurd for the prefetch methods then the DataTable can
implement the default loading bottom & top methods irregardless
of the whether the sub class actually wants to implement prefetch
=> windowed: tighten check for renderLoadingX

docs/bundle.js, docs/test.js, toggle/index.js
Currently toggle does not respect `checked={true|false}` on subsequent
re-renders.
This PR is very similar to https://github.com/optoolco/components/pull/43
Toggle will now respect the properties upon reRender instead of treating
the `checked` value as an "initial value"
=> src/toggle: Make toggle re-render safe

chart/README.md, chart/index.js, chart/test.js
The tonic-chart component currently uses dynamicRequire to
load the chart.js library.
This confuses the bundling tooling like `noderify` which means
that the `tonic-chart` component works in our electron app EXCEPT
when we bundle it into a package app binary with an `app.asar`.
By passing the `require('chart.js')` library as either a HTML
attribute or as a `setChart()` method we can require the `chart.js`
library in our app, have that picked up by the bundler without
a dynamic require statement and have the `tonic-chart` working
in the packaged version of our app.
=> chart: Support bundling of tonic-chart

windowed/index.js
Do not throw an error if the user requested to scroll to an
id that is no longer in `this.rows`;
=> src/windowed: Bail if scrolling to stale id.

docs/bundle.js, docs/test.js, input/test.js, package.json, tabs/index.js, tabs/test.js
The implementation of the tabs component eagerly
renders all the visual content, including the content
that's currently hidden.
These changes make it such that we do not actually
insert non-visible DOM elements into the document and
we only render them once the user changes the tab
and shows the content.
Also, when we change tabs back & forth we ensure
that we do not do extra unnecessary render calls on
the content.
=> tabs: Reduce amount of work done by default

input/index.js
If the user deletes the text such that the input has
the empty string then we must return the empty string
and not whater is in `this.props.value` which is the stale
value.
=> src/input: Handle empty string use case

dialog/README.md, dialog/index.js, dialog/readme.js, dist/index.js, docs/bundle.js, docs/examples.html, docs/test.js, input/index.js, loader/index.js, package.json, panel/index.js, panel/test.js
This bumps tonic and updates components.
The only breaking change I found was removing the
Tonic.raw() for labels in `<tonic-input>`. If you
want a non-text label you have to add your own `<label>`
adjacent to `<tonic-input>` instead of putting raw HTML
in the `label="..."` attribute of `tonic-input`.
r: @heapwolf
=> Upgrade to tonic@13

button/index.js, input/index.js, input/test.js
When the component reRendered it defaulted to
empty string even though there was text in the
input previously.
This is because the parent's parent reRendered
and the `_modified` is false as its a new DOM
element.
=> tonic-input was not working in wizard.

docs/src/markdown/events.md, package.json, test/fixtures/test-form.js, test/fixtures/testcafe.js, test/testcafe/test-form.ts
There were two issues in the example, using `detail`
for a builtin event and using `el.matches` instead of
`Tonic.match()`.
=> Update documentation for events.

button/index.js
The setter will now correctly set internal information
as well as update the DOM so that the user can see if
the button is disabled ore enabled.
The getter is simplified to just return what the user is
seeing, aka the current DOM attributes.
=> src/button: Update disable getter/setter.

select/index.js
This is necessary for multiple browser support, specifically
webkit
=> select: Remove old selected option attribute.

_dist/index.esm.js, _dist/index.js, input/test.js, split/index.js
This fixes an issue with tabbing behavior, previously content
in a splitter that was height 0 could be tabbed into which
would scroll the whole UI and cause confusion.
=> Set visibility hidden on split

_dist/index.esm.js, _dist/index.js, button/index.js
This means we can hover over disabled buttons and see their
title information show up. but once it is clicked we prevent
the behavior of the click itself.
=> button: Allow hovering over disabled buttons

relative-time/index.js
This fixes a failing test by parsing date strings when they are passed in.
=> Correctly parse date strings

package.json
This way pushing we don't forget to push during a publish, and end up with code in npm not in github.
=> Add a git push to the publish step
